# Generated by Django 5.2.13 on 2026-05-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('department', models.CharField(max_length=255)),
                ('specialization_areas', models.TextField(help_text='Comma-separated specialization areas')),
            ],
            options={
                'verbose_name': 'Supervisor',
                'verbose_name_plural': 'Supervisors',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
