# Generated by Django 5.2.13 on 2026-05-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JuryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('expertise_areas', models.JSONField(blank=True, default=list)),
                ('institution', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Jury Profile',
                'verbose_name_plural': 'Jury Profiles',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
