# Generated by Django 5.2.13 on 2026-05-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('expertise_areas', models.TextField(help_text='Comma-separated areas of expertise')),
                ('institution', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Jury Member',
                'verbose_name_plural': 'Jury Members',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
