# Generated by Django 5.2.13 on 2026-05-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('specialization', models.CharField(blank=True, max_length=255)),
                ('academic_year', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
